// Базовые определения квестов и вызовов

export const QUEST_DEFINITIONS = [
  // === ЕЖЕДНЕВНЫЕ ===
  {
    id: 'daily_morning_warrior',
    type: 'daily',
    period: 'day',
    title: 'Утренний воин',
    description: 'Выполните 3 задачи до 10:00.',
    group: 'daily',
    baseTarget: 3,
    autoActivate: true,
    rewards: { xp: 30, coins: 5, skillPoints: 0 },
  },
  {
    id: 'daily_evening_review',
    type: 'daily',
    period: 'day',
    title: 'Вечерний обзор',
    description: 'Завершите все важные задачи дня.',
    group: 'daily',
    baseTarget: 1,
    autoActivate: true,
    rewards: { xp: 40, coins: 5, skillPoints: 0 },
  },
  {
    id: 'daily_focus_marathon',
    type: 'daily',
    period: 'day',
    title: 'Фокус-марафон',
    description: 'Выполните 5 задач подряд, не сбрасывая серию фокуса.',
    group: 'daily',
    baseTarget: 5,
    autoActivate: true,
    rewards: { xp: 50, coins: 8, skillPoints: 0 },
  },
  {
    id: 'daily_german_minute',
    type: 'daily',
    period: 'day',
    title: 'Немецкая минута',
    description: 'Добавьте 5 новых слов в словарь за день.',
    group: 'daily',
    baseTarget: 5,
    autoActivate: true,
    rewards: { xp: 35, coins: 5, skillPoints: 0 },
  },

  // === ЕЖЕНЕДЕЛЬНЫЕ ===
  {
    id: 'weekly_productivity',
    type: 'weekly',
    period: 'week',
    title: 'Неделя продуктивности',
    description: 'Выполните 40 задач за последние 7 дней.',
    group: 'weekly',
    baseTarget: 40,
    autoActivate: true,
    rewards: { xp: 120, coins: 20, skillPoints: 1 },
  },
  {
    id: 'weekly_learning',
    type: 'weekly',
    period: 'week',
    title: 'Неделя обучения',
    description: 'Добавьте 30 немецких слов за последние 7 дней.',
    group: 'weekly',
    baseTarget: 30,
    autoActivate: true,
    rewards: { xp: 120, coins: 20, skillPoints: 1 },
  },
  {
    id: 'weekly_consistency',
    type: 'weekly',
    period: 'week',
    title: 'Неделя дисциплины',
    description: '7 дней подряд без пропусков (каждый день есть прогресс).',
    group: 'weekly',
    baseTarget: 7,
    autoActivate: true,
    rewards: { xp: 150, coins: 25, skillPoints: 1 },
  },
  {
    id: 'weekly_balance',
    type: 'weekly',
    period: 'week',
    title: 'Неделя баланса',
    description: 'Выполните задачи минимум из трёх разных категорий за 7 дней.',
    group: 'weekly',
    baseTarget: 3,
    autoActivate: true,
    rewards: { xp: 100, coins: 15, skillPoints: 1 },
  },

  // === СЮЖЕТНЫЕ ===
  {
    id: 'story_chapter_1',
    type: 'story',
    period: null,
    title: 'Глава 1: Начало пути',
    description: 'Достигните 5 уровня.',
    group: 'story',
    baseTarget: 5,
    autoActivate: true,
    rewards: { xp: 200, coins: 30, skillPoints: 1 },
  },
  {
    id: 'story_chapter_2',
    type: 'story',
    period: null,
    title: 'Глава 2: Первые победы',
    description: 'Получить 10 достижений (пока недоступно — готовится система достижений).',
    group: 'story',
    baseTarget: 10,
    autoActivate: false,
    rewards: { xp: 250, coins: 40, skillPoints: 1 },
  },
  {
    id: 'story_chapter_3',
    type: 'story',
    period: null,
    title: 'Глава 3: Становление мастера',
    description: 'Войти в золотую лигу (появится с системой лиг).',
    group: 'story',
    baseTarget: 1,
    autoActivate: false,
    rewards: { xp: 300, coins: 50, skillPoints: 2 },
  },
  {
    id: 'story_chapter_4',
    type: 'story',
    period: null,
    title: 'Глава 4: Легенда продуктивности',
    description: 'Создать свою систему продуктивности (будет связано с продвинутыми настройками).',
    group: 'story',
    baseTarget: 1,
    autoActivate: false,
    rewards: { xp: 400, coins: 80, skillPoints: 2 },
  },

  // === СЕЗОННЫЕ (пока как заготовки) ===
  {
    id: 'season_winter_marathon',
    type: 'season',
    period: 'month',
    title: 'Зимний марафон',
    description: 'Декабрьский челлендж продуктивности.',
    group: 'season',
    baseTarget: 60,
    autoActivate: false,
    rewards: { xp: 200, coins: 40, skillPoints: 1 },
  },
  {
    id: 'season_spring_refresh',
    type: 'season',
    period: 'month',
    title: 'Весеннее обновление',
    description: 'Мартовские цели и обновление привычек.',
    group: 'season',
    baseTarget: 50,
    autoActivate: false,
    rewards: { xp: 200, coins: 40, skillPoints: 1 },
  },
  {
    id: 'season_summer_productivity',
    type: 'season',
    period: 'month',
    title: 'Летняя продуктивность',
    description: 'Больше задач на свежем воздухе.',
    group: 'season',
    baseTarget: 50,
    autoActivate: false,
    rewards: { xp: 200, coins: 40, skillPoints: 1 },
  },
  {
    id: 'season_autumn_focus',
    type: 'season',
    period: 'month',
    title: 'Осенний фокус',
    description: 'Подготовка к зиме и фокус на важных целях.',
    group: 'season',
    baseTarget: 50,
    autoActivate: false,
    rewards: { xp: 200, coins: 40, skillPoints: 1 },
  },

  // === СПЕЦИАЛЬНЫЕ МИССИИ ===
  {
    id: 'special_rescue',
    type: 'special',
    period: null,
    title: 'Спасательная операция',
    description: 'Завершите 5 просроченных задач (старше 7 дней).',
    group: 'special',
    baseTarget: 5,
    autoActivate: true,
    rewards: { xp: 120, coins: 20, skillPoints: 1 },
  },
  {
    id: 'special_survival',
    type: 'special',
    period: null,
    title: 'Квест на выживание',
    description: '7 дней подряд без пропусков.',
    group: 'special',
    baseTarget: 7,
    autoActivate: true,
    rewards: { xp: 180, coins: 30, skillPoints: 1 },
  },
  {
    id: 'special_expedition',
    type: 'special',
    period: null,
    title: 'Экспедиция в неизвестное',
    description: 'Попробуйте все типы задач (разные категории).',
    group: 'special',
    baseTarget: 4,
    autoActivate: true,
    rewards: { xp: 150, coins: 25, skillPoints: 1 },
  },
  {
    id: 'special_boss_fight',
    type: 'special',
    period: 'week',
    title: 'Босс-битва',
    description: 'Завершите самую сложную задачу недели (задача с высоким XP).',
    group: 'special',
    baseTarget: 1,
    autoActivate: true,
    rewards: { xp: 200, coins: 35, skillPoints: 1 },
  },
];

